# Generated by Django 4.2.16 on 2024-09-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_nme_item_name_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_soold',
            new_name='is_sold',
        ),
    ]
